// generated by Fast Light User Interface Designer (fluid) version 1.0304

#ifndef gui_h
#define gui_h
#include <FL/Fl.H>
#include <FL/Fl_Double_Window.H>
#include "Application.h"
#include <stdlib.h>
#include <FL/Fl_Menu_Bar.H>
#include "EditorWindow.h"
#include "DisplayWindow.h"

class Gui {
public:
  Gui();
  Fl_Double_Window *MainWindow;
  Fl_Menu_Bar *menuBar;
  static Fl_Menu_Item menu_menuBar[];
  static Fl_Menu_Item *fileMenu;
  static Fl_Menu_Item *readFile;
private:
  inline void cb_readFile_i(Fl_Menu_*, void*);
  static void cb_readFile(Fl_Menu_*, void*);
public:
  static Fl_Menu_Item *writeFile;
private:
  inline void cb_writeFile_i(Fl_Menu_*, void*);
  static void cb_writeFile(Fl_Menu_*, void*);
public:
  static Fl_Menu_Item *exitButton;
private:
  inline void cb_exitButton_i(Fl_Menu_*, void*);
  static void cb_exitButton(Fl_Menu_*, void*);
public:
  static Fl_Menu_Item *imageProcessing;
  static Fl_Menu_Item *updateImage;
private:
  inline void cb_updateImage_i(Fl_Menu_*, void*);
  static void cb_updateImage(Fl_Menu_*, void*);
public:
  static Fl_Menu_Item *averageSmoothing;
private:
  inline void cb_averageSmoothing_i(Fl_Menu_*, void*);
  static void cb_averageSmoothing(Fl_Menu_*, void*);
public:
  static Fl_Menu_Item *medianSmoothing;
private:
  inline void cb_medianSmoothing_i(Fl_Menu_*, void*);
  static void cb_medianSmoothing(Fl_Menu_*, void*);
public:
  static Fl_Menu_Item *gaussianSmooth;
private:
  inline void cb_gaussianSmooth_i(Fl_Menu_*, void*);
  static void cb_gaussianSmooth(Fl_Menu_*, void*);
public:
  static Fl_Menu_Item *edgeDetection;
private:
  inline void cb_edgeDetection_i(Fl_Menu_*, void*);
  static void cb_edgeDetection(Fl_Menu_*, void*);
public:
  static Fl_Menu_Item *undo;
private:
  inline void cb_undo_i(Fl_Menu_*, void*);
  static void cb_undo(Fl_Menu_*, void*);
public:
  static Fl_Menu_Item *volumeRendering;
  static Fl_Menu_Item *readVolumeFile;
private:
  inline void cb_readVolumeFile_i(Fl_Menu_*, void*);
  static void cb_readVolumeFile(Fl_Menu_*, void*);
  inline void cb_X_i(Fl_Menu_*, void*);
  static void cb_X(Fl_Menu_*, void*);
public:
  static Fl_Menu_Item *MIP;
private:
  inline void cb_MIP_i(Fl_Menu_*, void*);
  static void cb_MIP(Fl_Menu_*, void*);
public:
  CEditorWindow *EditorWindow;
  CDisplayWindow *DisplayWindow;
  void show();
  Application *app; 
};
#endif
